### PR TITLE
Split Django settings

### PR DESCRIPTION
**Pull request by iflare3g**
- Split django settings into base, dev, test and prod
- The default one is the dev settings so in Production must be specified the settings module by DJANGO_SETTINGS_MODULE env variable or for example you can change the settings when running the runserver via --settings option

### CODE REVIEW

**Comment by psalmskalu** [comment]
Your change is conflicting. Some changes have been made to the settings.py file. Kindly pull the project again and split the settings with the new values to be merged

**Comment by iflare3g** [comment]
But why closing the PR before giving me the time to update it according to your feedbacks ?

**Comment by psalmskalu** [comment]
Sorry about that. Kindly clone again and make necessary changes. We were cleaning up to remove spam PRs

**Comment by iflare3g** [comment]
Ok nice, thanks for response!

**Pull request closed without merging**
